// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CancelDownload():Promise<void>;

export function OpenOutputFile(arg1:string):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function SelectTSListFile():Promise<string>;

export function StartDownload(arg1:gui.DownloadRequest):Promise<void>;
