// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['gui']['Backend']['CancelDownload']();
}

export function OpenOutputFile(arg1) {
  return window['go']['gui']['Backend']['OpenOutputFile'](arg1);
}

export function SelectOutputDir() {
  return window['go']['gui']['Backend']['SelectOutputDir']();
}

export function SelectTSListFile() {
  return window['go']['gui']['Backend']['SelectTSListFile']();
}

export function StartDownload(arg1) {
  return window['go']['gui']['Backend']['StartDownload'](arg1);
}
